[openpasslite]
host = "0.0.0.0"
port = 2177
cors_origin = "*"
debug = false
logfile_path = "logs/openpasslite.txt"

[smartfields]
host = "0.0.0.0"
port = 2188
cors_origin = "*"
debug = false
logfile_path = "logs/smartfields.txt"

[wildwings]
host = "0.0.0.0"
port = 2199
cors_origin = "*"
debug = false
logfile_path = "logs/wildwings.txt"

[subscriber]
client_id = "local_subscriber"
qos = 1
broker = "localhost"
port = 1883
logfile_path = "logs/mqtt_subscriber.txt" 
smartfields_url = "http://smartfields:2188/initiate_process"

# MQTT topic mapping for each Pi
[mqtt_topics."cameratrap/events"]
lat = 40.00788092013576
lon = -83.01784213632345
camid = "pi-001"

#[mqtt_topics."pi/002/events"]
#lat = 40.00811
#lon = -83.01809
#camid = "pi-002"